name: play35
dependencies:
- decorator=4.0.9=py35_0
- ipython_genutils=0.1.0=py35_0
- openssl=1.0.2g=0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.0.3=py35_0
- py=1.4.31=py35_0
- pytest=2.8.5=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=20.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0

