name: play35
dependencies:
- alabaster=0.7.7=py35_0
- appnope=0.1.0=py35_0
- babel=2.2.0=py35_0
- decorator=4.0.9=py35_0
- docutils=0.12=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.2.1=py35_0
- jupyter_core=4.1.0=py35_0
- markupsafe=0.23=py35_0
- mistune=0.7.2=py35_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_1
- openssl=1.0.2g=0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.0=py35_0
- ptyprocess=0.5=py35_0
- py=1.4.31=py35_0
- pygments=2.1.1=py35_0
- pytest=2.8.5=py35_0
- python=3.5.1=0
- python.app=1.2=py35_4
- pytz=2015.7=py35_0
- pyzmq=15.2.0=py35_0
- readline=6.2=2
- setuptools=20.2.2=py35_0
- simplegeneric=0.8.1=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.1
  - jupyter-core==4.1.0
  - sphinx-rtd-theme==0.1.9

